### ISSUE TITLE
Import/export of arbitrary tables

### ISSUE THREAD

**Issue by mbrodala** [MaxServ/t3ext-yaml-configuration#1]
Instead of being limited to backend/frontend users (groups) this one could be extended to allow importing and exporting arbitrary tables.

Aside from being able to completely set up a site with data from YAML files, this could also be handy for setting up temporariy instances during acceptance tests. Usually one uses an SQL dump here which is unwieldy and hard to track in VCS.

**Comment by Tuurlijk** [comment]
Done!

**Comment by mbrodala** [comment]
With 6f25e7bedd5c13734077d4e1c211ad2bfa63a842 I assume? Thanks a lot! :-)

**Comment by mbrodala** [comment]
Hint: Add `Fixes #NNN` to your commit message to have Github close issues automatically.
