### ISSUE TITLE
2 bugs when exporting backend users

### ISSUE THREAD

**Issue by oliverschroeder** [MaxServ/t3ext-yaml-configuration#22]
When exporting backend users, the assigned user groups (field usergroup) are exported by title since PR #21.

1. When only one usergroup is assigned the uid is used (instead of the title).
2. When collecting backendgroup titles the data array isn't reset, so all backendend groups assigned to all previous users are attached when exporting backendusers in the loop.

**Comment by Tuurlijk** [comment]
Thx
