### ISSUE TITLE
Feature request: Option to use uid's to match usergroups when exporting users

### ISSUE THREAD

**Issue by oliverschroeder** [MaxServ/t3ext-yaml-configuration#24]
Our use case is:

Multiple installations with identical backend group structrure and we're using PageTSconfig to set permissions (witch uses backend group uid's).

I'd like to introduce the option "--be-user-match-group-by-title" in order to control how backend groups are exported (by title or uid) when exporting backend users.

I'm currently working on this feature and will provide a pull request.

Regards,
Oliver

**Comment by Tuurlijk** [comment]
Merged, thx.
