### ISSUE TITLE
Content of type "list" not allowed in that column! (TYPO3 8.7.17)

### ISSUE THREAD

**Issue by misterboe** [MaxServ/t3ext-yaml-configuration#29]
When yaml_configuration is installed:

Click copy on an content element (small icon in page view) > Click on the icon again and choose `Paste copy after` brings the following errors. 
 
```
Content of type "list" not allowed in that column!
You are not allowed to place elements of type "list" in that column. Allowed items: "". You are an admin so this time I will see it through the fingers . . . but boy oh boy . . . naughty naughty!
```

```
Plugins of type "news_pi1" not allowed in that column!
You are not allowed to place elements of type "news_pi1" in that column. Allowed items: "". You are an admin so this time I will see it through the fingers . . . but boy oh boy . . . naughty naughty!
```

**Comment by Tuurlijk** [comment]
This pr should fix that: https://github.com/MaxServ/t3ext-yaml-configuration/pull/30

**Comment by Tuurlijk** [comment]
@haassie plx close this issue ;-)

**Comment by haassie** [comment]
Ah this issue wasn't mentioned in the PR so it does not automatically close. Will close it now.

**Comment by simare** [comment]
Hi, 
it seems the change is only on master. Could you add a bugfix relase-tag?

Thanks!
