### ISSUE TITLE
[v2] (Re-)add exploded columns feature

### ISSUE THREAD

**Issue by cumuru** [MaxServ/t3ext-yaml-configuration#45]
# Problem description
Exporting e.g. backend groups in v1, string columns that contained a comma were exploded by default, e.g. file permissions. This lead to e.g.
```
  file_permissions:
    - readFolder
    - writeFolder
    - addFolder
    - renameFolder
```
which is much more readable and better for VCS than the current v2 output:
```
  file_permissions: 'readFolder,writeFolder,addFolder,renameFolder'
```
On the other hand, columns like `TSconfig` were split, too, despite the fact it doesn‘t make any sense there.

# Proposed solution
I propose to make exploding columns explicit. That means introducing a new option that enumerates columns that should be exploded. So you could call e.g. `typo3 yaml:export --explode-columns=file_permissions,explicit_allowdeny` to have those fields split at commas.
Please note that the import can deal with YAML arrays with no extra configuration.

I‘ll open a PR.

**Comment by josefglatz** [comment]
Thanks for your PR. Already merged.
